name: student_marketplace_presentation
description: A student-oriented marketplace with base functionalities for buying and selling objects.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Business Logic
  student_marketplace_business_logic:
    path: ../student_marketplace_business_logic

  # Utilities
  dartz: 
  equatable:
  image_picker: ^0.8.6+3 
  get_it: 
  flutter_bloc: 
  shared_preferences: ^2.0.17

  # UI
  cupertino_icons: ^1.0.2
  flutter_platform_widgets: 
  drop_down_list: ^0.0.4
  flutter_image_compress: ^1.1.3
  flutter_slidable: ^2.0.0
  settings_ui: ^2.0.2
  like_button: ^2.0.5
  photo_view: ^0.14.0
  liquid_pull_to_refresh: ^3.0.1
  google_fonts: ^4.0.3
  animations: ^2.0.7
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  toggle_switch: ^2.0.1
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  

  # Testing
  mockito: ^5.4.0
  build_runner: ^2.3.3
  bloc_test: ^9.1.1
  test: ^1.22.0
  chat_bubbles: ^1.4.1
  animated_toggle_switch: ^0.6.2
  flutter_launcher_icons: ^0.13.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/