name: student_marketplace_presentation
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Business Logic
  student_marketplace_business_logic:
    path: ../student_marketplace_business_logic

  # Utilities
  dartz: 
  equatable:
  image_picker: ^0.8.6+3 
  get_it: 
  flutter_bloc: 
  shared_preferences: ^2.0.17

  # UI
  flutter_platform_widgets: 
  toggle_switch: ^2.0.1
  drop_down_list: ^0.0.4
  flutter_image_compress: ^1.1.3
  # auto_animated: ^3.1.0
  flutter_slidable: ^2.0.0
  settings_ui: ^2.0.2
  like_button: ^2.0.5
  photo_view: ^0.14.0
  liquid_pull_to_refresh: ^3.0.1
  google_fonts: ^4.0.3
  animations: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/