name: student_marketplace_frontend
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_platform_widgets: 
  http: 
  dartz: 
  equatable:
  image_picker: ^0.8.6+3 
  get_it: 
  flutter_bloc: 
  shared_preferences: ^2.0.17
  toggle_switch: ^2.0.1
  drop_down_list: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3  
  mockito: ^5.3.2


flutter:
  uses-material-design: true

